server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://10.200.10.210:6301/users_test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: test_rw
    password: test_rw
    driver-class-name: com.mysql.cj.jdbc.Driver
